services:
  - type: web
    name: smart-samarpan-academy
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20"
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
